group 'dev.zsz.flutter_esp'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.1'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'dev.zsz.flutter_esp'

    compileSdk = 35

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdk = 23
    }

    dependencies{
        implementation 'com.github.espressif:esp-idf-provisioning-android:lib-2.2.3'
        implementation 'org.greenrobot:eventbus:3.3.1'
    }
}

